### ISSUE TITLE
Detected  v9.8

### ISSUE THREAD

**Issue by Guun0x** [LostSoulFly/MinerProxy#12]
Thank you for very useful project.

But it's detected by Claymore's v9.8 . miner says nothing but silently dropped a "shares per hour" by 10-15% with the same hashrate.
But there is a solution how to bypass it.
Don't use a localhost,
just create a fake WAN by this method [Creating a fake WAN](https://github.com/JuicyPasta/Claymore-No-Fee-Proxy/wiki/Creating-a-fake-WAN-network-(Win))

added: Seems this method is detected too

**Comment by LostSoulFly** [comment]
From the readme:

> My personal solution involves using my external, public IP address as my pool address in my mining software, with port forwarding enabled on my router to redirect the connections to MinerProxy. With this, Claymore doesn't seem to realize it's a local proxy and most importantly, stale shares drop significantly.
