### ISSUE TITLE
Tested Pools list

### ISSUE THREAD

**Issue by kiwina** [LostSoulFly/MinerProxy#13]
Lets write up all pools that get tested over here.
ETH ethpool.org OK
ZEC flypool OK

**Comment by LostSoulFly** [comment]
Most pools should work, so long as MinerProxy is configured correctly.
I've used UBQ.pool.sexy, madmining.com, hushpool, miningspeed, ethermine, suprnova, and a few more.

**Comment by mlgitdev** [comment]
Dwarfpool - ZEC, Eth | OK
Ubiqpool.io - UBIQ | OK
