### ISSUE TITLE
Stale shares

### ISSUE THREAD

**Issue by kiwina** [LostSoulFly/MinerProxy#14]
for some reason witch i think must be the proxy once i start adding say 30 miners i get in average > 4% stale shares and i know it is not the network as its a gigabit line all on cat 6 cables fast router

**Comment by LostSoulFly** [comment]
https://github.com/LostSoulFly/MinerProxy#stale-shares

**Comment by kiwina** [comment]
no actually im not even using claymore i use ethermine, and all miners have a healthy amount of stale share

**Comment by LostSoulFly** [comment]
https://github.com/ethereum-mining/ethminer/issues/141

I'm afraid I don't have an answer for you. Ethermine isn't a software, it's a website, so I can only assume you mean ethminer, which I unfortunately do not use. You should check the debug output/log file to see if there are any errors popping up, and give it some more time to regulate itself.
