### ISSUE TITLE
Claymore v10

### ISSUE THREAD

**Issue by lcheung90** [LostSoulFly/MinerProxy#15]
When the DevFee connection is made the wallet is not being replaced. (175.5.10.15 is my fake WAN)
![clay](https://user-images.githubusercontent.com/1421411/31619650-08fe124c-b24a-11e7-8497-5ae9653b0c4f.PNG)

After leaving it run for a couple hours, the miner reverts to no-devfee mode.
![capture pngasdfa](https://user-images.githubusercontent.com/1421411/31619833-86d48bce-b24a-11e7-8795-5a325984aed7.PNG)

Any ideas?

**Comment by LostSoulFly** [comment]
I do not use the same method that you do, but I would assume that it is your issue.

Try it with using a 127.0.0.1 (or the IP of the computer with MinerProxy). It also doesn't look like your config for MinerProxy is setup properly -- it shouldn't detect "DevFee" with the correct wallet.

**Comment by patofet** [comment]
I have the exact same thing, I must set "-nofee 1" in order to avoid the error, I don't care about claymore fee but I can't use MinerProxy with fee activated
