### ISSUE TITLE
XMR Nicehash not working?

### ISSUE THREAD

**Issue by verybigfurrymonster2** [LostSoulFly/MinerProxy#17]
I tried with these settings but the miner looses connection

{
  "allowedAddresses": [
    "127.0.0.1",
    "0.0.0.0"
  ],
  "poolList": [
    {
      "poolAddress": "cryptonight.jp.nicehash.com",
      "poolPort": 33355 
    }
  ],
  "proxyListenPort": 9000,
  "webSocketPort": 9091,
  "log": false,
  "debug": true,
  "identifyDevFee": true,
  "showEndpointInConsole": true,
  "showRigStats": true,
  "useDotWithRigName": false,
  "useSlashWithRigName": false,
  "useWorkerWithRigName": false,
  "colorizeConsole": true,
  "replaceWallet": true,
  "useWebSockServer": true,
  "usePasswordAsRigName": false,
  "donateDevFee": false,
  "useRigNameAsEndPoint": false,
  "percentToDonate": 0,
  "rigStatsIntervalSeconds": 60,
  "walletAddress": "mywallet",
  "devFeeWalletAddress": "",
  "minedCoin": "XMR"
}

Logs from xmr miner

SOCKET-ERROR Receive socket closed

**Comment by LostSoulFly** [comment]
You should enable Debug, press D in console before the miner connects.

It's probably an unexpected response from the server, though I'm not sure
how using Monero to Nicehash would work. You may want to try using NICEHASH
as the minedCoin.

I'm sorry I can't be of more help, I've never tried Nicehash personally.
