### ISSUE TITLE
Allow switching of pools

### ISSUE THREAD

**Issue by LostSoulFly** [LostSoulFly/MinerProxy#2]
By either a timer, manually, or automatically if shares aren't being accepted by the current server.

**Comment by LostSoulFly** [comment]
Partially implemented. The ability to change pools is now working.

My next step will be to determine how I want to handle doing it by timer, manually will likely be done through the web UI.

If anyone has any input, let me know. Should I create a settings option for pools and allow cycling through them at a set interval or as failover, or what? I think there would be some issues with just switching pools without disconnecting the client, because the server could get some unrequested work and the server would close the connection.

**Comment by hogze94** [comment]
fail over.

If you are going to cycle during intervals then make it cycle after submitting work or receiving new get work.

**Comment by LostSoulFly** [comment]
For fail over, waiting for a submitWork or getWork would certainly be something to try. Could even suppress submitWork's from reaching the new pool until work was received from the new pool.
