### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by dandare76** [LostSoulFly/MinerProxy#5]
1>------ Build started: Project: MinerProxy, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Lucru\MinerProxy-master\MinerProxy\CoinHandlers\EthCoin.cs(4,7,4,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Lucru\MinerProxy-master\MinerProxy\CoinHandlers\NiceHash.cs(4,7,4,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Lucru\MinerProxy-master\MinerProxy\Redirector.cs(4,7,4,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Lucru\MinerProxy-master\MinerProxy\Settings.cs(1,7,1,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by LostSoulFly** [comment]
You're missing JSON.net
![image](https://user-images.githubusercontent.com/9120519/27433280-11a56fd6-5722-11e7-8048-a19e4f385a74.png)

Then install/update to 10.0.3.
![image](https://user-images.githubusercontent.com/9120519/27433320-342c3396-5722-11e7-992c-7abc108e9aae.png)

**Comment by dandare76** [comment]
Thank you very much!
