### ISSUE TITLE
DevFee donation issue

### ISSUE THREAD

**Issue by samut3** [LostSoulFly/MinerProxy#6]
If the pool the user is mining in uses slash for worker name, it won't work for ethermine.
It makes an error when connecting: "Server error for DevFee: Invalid user provided"

**Comment by LostSoulFly** [comment]
Hmm. I don't quite understand. Ethermine doesn't use slashes from my experience..

**Comment by samut3** [comment]
That's the problem. Ethermine uses dots. So if the pool the user mines in uses slash, it will try to use a slash for Ethermine when donating, and it will disconnect with an error.

**Comment by LostSoulFly** [comment]
I believe I've resolved this with a simple fix, now it just replaces the wallet altogether at the end.

Good catch 👍
