### ISSUE TITLE
DonateFee

### ISSUE THREAD

**Issue by hogze94** [LostSoulFly/MinerProxy#8]
Trying to figure out the code, is the donate fee a % of DevFee?
It seems to only switch to donate on login which only changes when the miner program switches to dev fee mode.

**Comment by LostSoulFly** [comment]
Yes, it's a percentage chance on each new connection that is identified as a DevFee. This means that only DevFee connections from Claymore or another mining program would be eligible for donation, and even then it would have to fall within the very small percentage window.

A connection that is **not** identified as a DevFee will **not** be considered for donation percentage.

**Comment by hogze94** [comment]
to clarify, claymore is 1%.Ive replaced it with my wallet. if i set the proxy donation to 50%, you will get 0.5%?

i think better explanation is required, currently i think with my setting you are getting 1% of 1% due to misunderstanding.

**Comment by LostSoulFly** [comment]
> Claymore DevFee fee is 1% for Ethereum-only mining mode and 2% for dual mining mode, every hour the miner mines for 36 or 72 seconds for developer. 

And with MinerProxy, only those once per hour DevFee connections are considered for donation. So, if you set "percentToDonate" to 50 then you would be donating the DevFee 50% of the time, and keeping the DevFee 50% of the time.

Basically, you have an percentToDonate% chance of donating the DevFee once per hour.

By the way, are you icecubec?

**Comment by hogze94** [comment]
no, and thanks for the clarification
